// JAGO Multilingual Localization Engine
// Covers Top 7 Official Languages of India

export const TOP_LANGUAGES = [
  { code: 'en', label: 'English', nativeName: 'English', region: 'National / Official' },
  { code: 'hi', label: 'Hindi', nativeName: 'हिन्दी', region: 'North / Central India' },
  { code: 'bn', label: 'Bengali', nativeName: 'বাংলা', region: 'West Bengal / East India' },
  { code: 'mr', label: 'Marathi', nativeName: 'मराठी', region: 'Maharashtra / Western India' },
  { code: 'te', label: 'Telugu', nativeName: 'తెలుగు', region: 'Andhra Pradesh / Telangana' },
  { code: 'ta', label: 'Tamil', nativeName: 'தமிழ்', region: 'Tamil Nadu / South India' },
  { code: 'gu', label: 'Gujarati', nativeName: 'ગુજરાતી', region: 'Gujarat / Western India' },
];

export const translations = {
  en: {
    appTitle: 'JAGO',
    appSubtitle: 'Unified Scholarship Intelligence for ST Students',
    ministryTitle: 'Ministry of Tribal Affairs • Government of India',
    oneStudentSubtitle: 'One Student. One View. Zero Repetition.',
    offlineModeActive: 'Offline Mode Active: Local Data Preserved',
    welcome: 'Namaste',
    verified: 'Aadhaar Verified',
    disbursed: 'Disbursed (DBT)',
    sanctioned: 'Sanctioned (Pending)',
    creditedToSbi: 'Credited to Bank Account',
    underReview: 'Expected DBT Credit',
    quickServices: 'Quick Services',
    viewAllSchemes: 'All 5 Schemes →',
    myApplications: 'My Applications',
    noApps: 'No Applications Yet',
    exploreApply: 'Explore & Apply',
    appliedOn: 'Applied on',
    viewTimeline: 'View Timeline',
    nationalImpact: 'Ministry of Tribal Affairs • National DBT Impact',
    dbtHistory: 'Direct Benefit Transfer History',
    recentApplications: 'Recent Applications',
    actionRequired: 'Action Required',
    deficiencyNotice: 'Deficiency Notice',
    rectifyNow: 'Rectify Now',
    fixViaWallet: 'Fix via Wallet →',

    // Scheme Directory
    exploreSchemes: 'Explore ST Scholarship Programs',
    schemeDirectory: 'Unified Scheme Directory',
    motaCentralSchemes: '5 MoTA Central Schemes',
    searchSchemesPlaceholder: 'Search by scheme name, degree or institute...',
    filterAll: 'All Schemes',
    filterNsp: 'NSP Portal',
    filterSfmp: 'SFMP (Canara)',
    filterNos: 'NOS Portal',
    daysLeft: 'days left',
    deadlinePassed: 'Deadline passed',
    applyNow: 'Apply Now',
    academicYear: 'Academic Year',
    noSchemesFound: 'No scholarship schemes match your search criteria.',

    // Document Wallet
    docWalletTitle: 'Document Wallet',
    syncDigilocker: 'Sync with DigiLocker',
    uploadNewDoc: 'Upload New Document',
    digilockerVerified: 'DigiLocker Verified',
    zeroKnowledgeEncrypted: 'Zero-Knowledge Encrypted (AES-256)',
    catAll: 'All Documents',
    catIdentity: 'Identity',
    catCaste: 'Caste',
    catIncome: 'Income',
    catAcademic: 'Academic',

    // Application Tracker
    trackerTitle: 'Application Tracker',
    activeApplications: 'Active Applications',
    noActiveApplications: 'No active scholarship applications found.',
    stage1: 'Registration & Identity Verification',
    stage2: 'Institute AISHE Authentication',
    stage3: 'State Tribal Department Verification',
    stage4: 'Central Ministry Sanction Order',
    stage5: 'DBT Direct Disbursal to Bank Account',
    statusSanctioned: 'Sanctioned',
    statusDisbursed: 'Disbursed',
    statusDeficiency: 'Deficiency',
    statusPending: 'Pending',
    statusApproved: 'Approved',
    statusCompleted: 'Completed',
    statusInProgress: 'In Progress',

    // Profile
    profileTitle: 'Applicant Profile',
    personalDetails: 'Personal Information',
    tribalDetails: 'Tribal & Community Details',
    educationDetails: 'Current Education Enrolment',
    bankDetails: 'DBT Bank Account',
    securityEncryption: 'Security & Zero-Knowledge Encryption',
    editProfile: 'Edit Profile Details',
    saveProfile: 'Save Profile Changes',
    fullName: 'Full Name',
    fatherName: "Father's Name",
    mobile: 'Mobile Number',
    email: 'Email Address',
    state: 'State',
    district: 'District',
    annualIncome: 'Annual Family Income',
    institution: 'Institution',
    course: 'Course / Program',
    rollNo: 'Roll Number',
    bankName: 'Bank Name',
    accountNo: 'Account Number',
    ifsc: 'IFSC Code',
    dbtActive: 'Aadhaar DBT Active',

    // Bottom Nav
    navHome: 'Home',
    navSchemes: 'Schemes',
    navTrack: 'Track',
    navDocs: 'Docs',
    navProfile: 'Profile',

    // Quick Actions
    actionApply: 'Apply Now',
    actionExplore: 'Explore Schemes',
    actionTrack: 'Track Status',
    actionWallet: 'Doc Wallet',
    actionJago: 'JAGO Assistant',
    actionEligibility: 'Eligibility Check',

    // Assistant
    chatbotGreeting: 'Namaste! 🙏 I am JAGO, your verified virtual assistant for Ministry of Tribal Affairs scholarships. How can I help you today?',
    chatbotPlaceholder: 'Ask JAGO anything about scholarships...',
    chatbotSend: 'Send',

    // Settings & Notifications
    language: 'Language',
    changeLanguage: 'Change App Language',
    currentLanguage: 'Current Language',
    notificationsTitle: 'Notification Center',
    markAllRead: 'Mark all as read',
  },

  hi: {
    appTitle: 'जागो (JAGO)',
    appSubtitle: 'जनजातीय छात्रों के लिए एकीकृत छात्रवृत्ति प्रणाली',
    ministryTitle: 'जनजातीय कार्य मंत्रालय • भारत सरकार',
    oneStudentSubtitle: 'एक छात्र। एक दृश्य। शून्य पुनरावृत्ति।',
    offlineModeActive: 'ऑफलाइन मोड सक्रिय: स्थानीय डेटा सुरक्षित',
    welcome: 'नमस्ते',
    verified: 'आधार सत्यापित',
    disbursed: 'प्राप्त राशि (DBT)',
    sanctioned: 'स्वीकृत (प्रक्रिया में)',
    creditedToSbi: 'बैंक खाते में जमा',
    underReview: 'प्रत्याशित डीबीटी भुगतान',
    quickServices: 'त्वरित सेवाएं',
    viewAllSchemes: 'सभी 5 योजनाएं →',
    myApplications: 'मेरे आवेदन',
    noApps: 'अभी कोई आवेदन नहीं',
    exploreApply: 'खोजें और आवेदन करें',
    appliedOn: 'आवेदन तिथि',
    viewTimeline: 'स्थिति देखें',
    nationalImpact: 'जनजातीय कार्य मंत्रालय • राष्ट्रीय डीबीटी प्रभाव',
    dbtHistory: 'प्रत्यक्ष लाभ अंतरण (DBT) इतिहास',
    recentApplications: 'हालिया आवेदन',
    actionRequired: 'कार्रवाई आवश्यक',
    deficiencyNotice: 'त्रुटि सूचना (Deficiency)',
    rectifyNow: 'अभी सुधारें',
    fixViaWallet: 'वॉलेट से सुधारें →',

    // Scheme Directory
    exploreSchemes: 'अनुसूचित जनजाति छात्रवृत्ति योजनाएं खोजें',
    schemeDirectory: 'एकीकृत योजना निर्देशिका',
    motaCentralSchemes: '5 जनजातीय मंत्रालय केंद्रीय योजनाएं',
    searchSchemesPlaceholder: 'योजना का नाम, डिग्री या संस्थान खोजें...',
    filterAll: 'सभी योजनाएं',
    filterNsp: 'एनएसपी पोर्टल',
    filterSfmp: 'एसएफएमपी (केनरा)',
    filterNos: 'एनओएस पोर्टल',
    daysLeft: 'दिन शेष',
    deadlinePassed: 'समय सीमा समाप्त',
    applyNow: 'आवेदन करें',
    academicYear: 'शैक्षणिक वर्ष',
    noSchemesFound: 'आपके खोज मानदंडों से कोई छात्रवृत्ति योजना मेल नहीं खाती।',

    // Document Wallet
    docWalletTitle: 'दस्तावेज़ वॉलेट',
    syncDigilocker: 'डिजीलॉकर से सिंक करें',
    uploadNewDoc: 'नया दस्तावेज़ अपलोड करें',
    digilockerVerified: 'डिजीलॉकर सत्यापित',
    zeroKnowledgeEncrypted: 'ज़ीरो-नॉलेज एन्क्रिप्टेड (AES-256)',
    catAll: 'सभी दस्तावेज़',
    catIdentity: 'पहचान प्रमाण',
    catCaste: 'जाति प्रमाण पत्र',
    catIncome: 'आय प्रमाण पत्र',
    catAcademic: 'शैक्षणिक अंकपत्र',

    // Application Tracker
    trackerTitle: 'आवेदन ट्रैकर',
    activeApplications: 'सक्रिय आवेदन',
    noActiveApplications: 'कोई सक्रिय छात्रवृत्ति आवेदन नहीं मिला।',
    stage1: 'पंजीकरण एवं पहचान सत्यापन',
    stage2: 'संस्थान AISHE प्रमाणीकरण',
    stage3: 'राज्य जनजातीय विभाग सत्यापन',
    stage4: 'केंद्रीय मंत्रालय स्वीकृति आदेश',
    stage5: 'बैंक खाते में प्रत्यक्ष डीबीटी अंतरण',
    statusSanctioned: 'स्वीकृत',
    statusDisbursed: 'वितरित',
    statusDeficiency: 'त्रुटि (Deficiency)',
    statusPending: 'लंबित',
    statusApproved: 'अनुमोदित',
    statusCompleted: 'पूर्ण',
    statusInProgress: 'प्रगति पर',

    // Profile
    profileTitle: 'आवेदक प्रोफ़ाइल',
    personalDetails: 'व्यक्तिगत जानकारी',
    tribalDetails: 'जनजातीय एवं समुदाय विवरण',
    educationDetails: 'वर्तमान शैक्षणिक नामांकन',
    bankDetails: 'डीबीटी बैंक खाता',
    securityEncryption: 'सुरक्षा एवं ज़ीरो-नॉलेज एन्क्रिप्शन',
    editProfile: 'विवरण संपादित करें',
    saveProfile: 'बदलाव सुरक्षित करें',
    fullName: 'पूरा नाम',
    fatherName: 'पिता का नाम',
    mobile: 'मोबाइल नंबर',
    email: 'ईमेल पता',
    state: 'राज्य',
    district: 'जिला',
    annualIncome: 'वार्षिक पारिवारिक आय',
    institution: 'शिक्षण संस्थान',
    course: 'पाठ्यक्रम / डिग्री',
    rollNo: 'रोल नंबर',
    bankName: 'बैंक का नाम',
    accountNo: 'खाता संख्या',
    ifsc: 'आईएफएससी कोड',
    dbtActive: 'आधार डीबीटी सक्रिय',

    // Bottom Nav
    navHome: 'होम',
    navSchemes: 'योजनाएं',
    navTrack: 'ट्रैकर',
    navDocs: 'दस्तावेज़',
    navProfile: 'प्रोफ़ाइल',

    // Quick Actions
    actionApply: 'आवेदन करें',
    actionExplore: 'योजनाएं खोजें',
    actionTrack: 'आवेदन स्थिति',
    actionWallet: 'दस्तावेज़ वॉलेट',
    actionJago: 'जागो सहायक',
    actionEligibility: 'पात्रता जांचें',

    // Assistant
    chatbotGreeting: 'नमस्ते! 🙏 मैं जागो (JAGO) हूँ, जनजातीय कार्य मंत्रालय का छात्रवृत्ति सहायक। आज मैं आपकी क्या सहायता कर सकता हूँ?',
    chatbotPlaceholder: 'छात्रवृत्ति के बारे में कुछ भी पूछें...',
    chatbotSend: 'भेजें',

    // Settings & Notifications
    language: 'भाषा (Language)',
    changeLanguage: 'ऐप की भाषा बदलें',
    currentLanguage: 'वर्तमान भाषा',
    notificationsTitle: 'अधिसूचना केंद्र',
    markAllRead: 'सभी को पढ़ा हुआ चिह्नित करें',
  },

  bn: {
    appTitle: 'জাগো (JAGO)',
    appSubtitle: 'উপজাতি শিক্ষার্থীদের জন্য সমন্বিত স্কলারশিপ পোর্টাল',
    ministryTitle: 'জনজাতি বিষয়ক মন্ত্রক • ভারত সরকার',
    oneStudentSubtitle: 'এক শিক্ষার্থী। এক পোর্টাল। শূন্য পুনরাবৃত্তি।',
    offlineModeActive: 'অফলাইন মোড সক্রিয়: স্থানীয় ডেটা সংরক্ষিত',
    welcome: 'নমস্কার',
    verified: 'আধার যাচাইকৃত',
    disbursed: 'বিতরণকৃত (DBT)',
    sanctioned: 'অনুমোদিত (বিবেচনাধীন)',
    creditedToSbi: 'ব্যাঙ্ক অ্যাকাউন্টে জমা',
    underReview: 'প্রত্যাশিত ডিবিটি স্থানান্তর',
    quickServices: 'দ্রুত পরিষেবা',
    viewAllSchemes: 'সব ৫টি স্কিম →',
    myApplications: 'আমার আবেদনসমূহ',
    noApps: 'এখনও কোনো আবেদন নেই',
    exploreApply: 'খুঁজুন ও আবেদন করুন',
    appliedOn: 'আবেদনের তারিখ',
    viewTimeline: 'টাইমলাইন দেখুন',
    nationalImpact: 'জনজাতি বিষয়ক মন্ত্রক • জাতীয় ডিবিটি প্রভাব',
    dbtHistory: 'সরাসরি সুবিধা হস্তান্তর (DBT) ইতিহাস',
    recentApplications: 'সাম্প্রতিক আবেদনসমূহ',
    actionRequired: 'পদক্ষেপ প্রয়োজন',
    deficiencyNotice: 'ত্রুটি বিজ্ঞপ্তি (Deficiency)',
    rectifyNow: 'এখনই সংশোধন করুন',
    fixViaWallet: 'ওয়ালেট থেকে সংশোধন →',

    // Scheme Directory
    exploreSchemes: 'উপজাতি স্কলারশিপ স্কিমসমূহ খুঁজুন',
    schemeDirectory: 'সমন্বিত স্কিম নির্দেশিকা',
    motaCentralSchemes: '৫টি কেন্দ্রীয় জনজাতি মন্ত্রকের স্কিম',
    searchSchemesPlaceholder: 'স্কিমের নাম, ডিগ্রি বা প্রতিষ্ঠান খুঁজুন...',
    filterAll: 'সব স্কিম',
    filterNsp: 'NSP পোর্টাল',
    filterSfmp: 'SFMP (ক্যানারা)',
    filterNos: 'NOS পোর্টাল',
    daysLeft: 'দিন বাকি',
    deadlinePassed: 'সময়সীমা অতিক্রান্ত',
    applyNow: 'আবেদন করুন',
    academicYear: 'শিক্ষাবর্ষ',
    noSchemesFound: 'আপনার অনুসন্ধানের সাথে কোনো স্কিম মিলছে না।',

    // Document Wallet
    docWalletTitle: 'ডকুমেন্ট ওয়ালেট',
    syncDigilocker: 'ডিজিলকার থেকে সিঙ্ক করুন',
    uploadNewDoc: 'নতুন ডকুমেন্ট আপলোড',
    digilockerVerified: 'ডিজিলকার যাচাইকৃত',
    zeroKnowledgeEncrypted: 'জিরো-নলেজ এনক্রিপ্ট করা (AES-256)',
    catAll: 'সমস্ত নথি',
    catIdentity: 'পরিচয়পত্র',
    catCaste: 'জাতিগত শংসাপত্র',
    catIncome: 'আয় শংসাপত্র',
    catAcademic: 'শিক্ষাগত মার্কশিট',

    // Application Tracker
    trackerTitle: 'আবেদন ট্র্যাকার',
    activeApplications: 'সক্রিয় আবেদনসমূহ',
    noActiveApplications: 'কোনো সক্রিয় স্কলারশিপ আবেদন পাওয়া যায়নি।',
    stage1: 'নিবন্ধন ও পরিচয় যাচাইকরণ',
    stage2: 'প্রতিষ্ঠান AISHE অনুমোদন',
    stage3: 'রাজ্য উপজাতি কল্যাণ বিভাগ যাচাইকরণ',
    stage4: 'কেন্দ্রীয় মন্ত্রক অনুমোদন আদেশ',
    stage5: 'ব্যাঙ্ক অ্যাকাউন্টে সরাসরি ডিবিটি প্রদান',
    statusSanctioned: 'অনুমোদিত',
    statusDisbursed: 'বিতরণকৃত',
    statusDeficiency: 'ত্রুটি (Deficiency)',
    statusPending: 'বিবেচনাধীন',
    statusApproved: 'অনুমোদিত',
    statusCompleted: 'সম্পূর্ণ',
    statusInProgress: 'চলমান',

    // Profile
    profileTitle: 'আবেদনকারীর প্রোফাইল',
    personalDetails: 'ব্যক্তিগত তথ্য',
    tribalDetails: 'জনজাতি ও সম্প্রদায় সংক্রান্ত তথ্য',
    educationDetails: 'বর্তমান শিক্ষাগত তথ্য',
    bankDetails: 'ডিবিটি ব্যাঙ্ক অ্যাকাউন্ট',
    securityEncryption: 'নিরাপত্তা ও জিরো-নলেজ এনক্রিপশন',
    editProfile: 'প্রোফাইল সম্পাদনা করুন',
    saveProfile: 'পরিবর্তন সংরক্ষণ করুন',
    fullName: 'পূর্ণ নাম',
    fatherName: 'পিতার নাম',
    mobile: 'মোবাইল নম্বর',
    email: 'ইমেল ঠিকানা',
    state: 'রাজ্য',
    district: 'জেলা',
    annualIncome: 'বার্ষিক পারিবারিক আয়',
    institution: 'শিক্ষাপ্রতিষ্ঠান',
    course: 'কোর্স / পাঠ্যক্রম',
    rollNo: 'রোল নম্বর',
    bankName: 'ব্যাঙ্কের নাম',
    accountNo: 'অ্যাকাউন্ট নম্বর',
    ifsc: 'IFSC কোড',
    dbtActive: 'আধার ডিবিটি সক্রিয়',

    // Bottom Nav
    navHome: 'হোম',
    navSchemes: 'স্কিমসমূহ',
    navTrack: 'ট্র্যাক',
    navDocs: 'ডকুমেন্টস',
    navProfile: 'প্রোফাইল',

    // Quick Actions
    actionApply: 'আবেদন করুন',
    actionExplore: 'স্কিম সন্ধান',
    actionTrack: 'অবস্থা ট্র্যাক',
    actionWallet: 'ডক ওয়ালেট',
    actionJago: 'জাগো সহকারী',
    actionEligibility: 'যোগ্যতা পরীক্ষা',

    // Assistant
    chatbotGreeting: 'নমস্কার! 🙏 আমি জাগো (JAGO), জনজাতি বিষয়ক মন্ত্রকের স্কলারশিপ সহকারী। আপনাকে কীভাবে সাহায্য করতে পারি?',
    chatbotPlaceholder: 'স্কলারশিপ সংক্রান্ত যেকোনো প্রশ্ন লিখুন...',
    chatbotSend: 'পাঠান',

    // Settings & Notifications
    language: 'ভাষা (Language)',
    changeLanguage: 'অ্যাপের ভাষা পরিবর্তন করুন',
    currentLanguage: 'বর্তমান ভাষা',
    notificationsTitle: 'বিজ্ঞপ্তি কেন্দ্র',
    markAllRead: 'সবগুলি পঠিত হিসেবে চিহ্নিত করুন',
  },

  mr: {
    appTitle: 'जागो (JAGO)',
    appSubtitle: 'आदिवासी विद्यार्थ्यांसाठी एकात्मिक शिष्यवृत्ती प्रणाली',
    ministryTitle: 'आदिवासी कार्य मंत्रालय • भारत सरकार',
    oneStudentSubtitle: 'एक विद्यार्थी. एक पोर्टल. शून्य पुनरावृत्ती.',
    offlineModeActive: 'ऑफलाइन मोड सक्रिय: स्थानिक डेटा सुरक्षित',
    welcome: 'नमस्ते',
    verified: 'आधार प्रमाणित',
    disbursed: 'वितरित रक्कम (DBT)',
    sanctioned: 'मंजूर (प्रलंबित)',
    creditedToSbi: 'बँक खात्यात जमा',
    underReview: 'अपेक्षित डीबीटी जमा',
    quickServices: 'त्वरित सेवा',
    viewAllSchemes: 'सर्व ५ योजना →',
    myApplications: 'माझे अर्ज',
    noApps: 'अद्याप कोणतेही अर्ज नाहीत',
    exploreApply: 'शोधा आणि अर्ज करा',
    appliedOn: 'अर्ज तारीख',
    viewTimeline: 'प्रगती पहा',
    nationalImpact: 'आदिवासी कार्य मंत्रालय • राष्ट्रीय डीबीटी प्रभाव',
    dbtHistory: 'थेट लाभ हस्तांतरण (DBT) इतिहास',
    recentApplications: 'अलीकडील अर्ज',
    actionRequired: 'कारवाई आवश्यक',
    deficiencyNotice: 'त्रुटी सूचना (Deficiency)',
    rectifyNow: 'आता दुरुस्त करा',
    fixViaWallet: 'वॉलेटमधून दुरुस्त करा →',

    // Scheme Directory
    exploreSchemes: 'आदिवासी शिष्यवृत्ती योजना शोधा',
    schemeDirectory: 'एकात्मिक योजना निर्देशिका',
    motaCentralSchemes: '५ केंद्रीय आदिवासी मंत्रालय योजना',
    searchSchemesPlaceholder: 'योजनेचे नाव, पदवी किंवा संस्था शोधा...',
    filterAll: 'सर्व योजना',
    filterNsp: 'NSP पोर्टल',
    filterSfmp: 'SFMP (कॅनरा)',
    filterNos: 'NOS पोर्टल',
    daysLeft: 'दिवस शिल्लक',
    deadlinePassed: 'मुदत संपली',
    applyNow: 'अर्ज करा',
    academicYear: 'शैक्षणिक वर्ष',
    noSchemesFound: 'कोणतीही योजना जुळत नाही.',

    // Document Wallet
    docWalletTitle: 'कागदपत्रे पाकीट',
    syncDigilocker: 'डिजीलॉकरशी सिंक करा',
    uploadNewDoc: 'नवीन कागदपत्र अपलोड करा',
    digilockerVerified: 'डिजीलॉकर प्रमाणित',
    zeroKnowledgeEncrypted: 'झिरो-नॉलेज एन्क्रिप्टेड (AES-256)',
    catAll: 'सर्व कागदपत्रे',
    catIdentity: 'ओळखपत्र',
    catCaste: 'जातीचा दाखला',
    catIncome: 'उत्पन्नाचा दाखला',
    catAcademic: 'शैक्षणिक गुणपत्रिका',

    // Application Tracker
    trackerTitle: 'अर्ज ट्रॅकर',
    activeApplications: 'सक्रिय अर्ज',
    noActiveApplications: 'कोणताही सक्रिय अर्ज आढळला नाही.',
    stage1: 'नोंदणी व ओळख पडताळणी',
    stage2: 'संस्था AISHE प्रमाणीकरण',
    stage3: 'राज्य आदिवासी विभाग पडताळणी',
    stage4: 'केंद्रीय मंत्रालय मंजुरी आदेश',
    stage5: 'बँक खात्यात थेट डीबीटी जमा',
    statusSanctioned: 'मंजूर',
    statusDisbursed: 'वितरित',
    statusDeficiency: 'त्रुटी',
    statusPending: 'प्रलंबित',
    statusApproved: 'मंजूर',
    statusCompleted: 'पूर्ण',
    statusInProgress: 'प्रगतीपथावर',

    // Profile
    profileTitle: 'अर्जदार प्रोफाइल',
    personalDetails: 'वैयक्तिक माहिती',
    tribalDetails: 'आदिवासी आणि समाज तपशील',
    educationDetails: 'सध्याचे शैक्षणिक नावनोंदणी',
    bankDetails: 'डीबीटी बँक खाते',
    securityEncryption: 'सुरक्षा आणि झिरो-नॉलेज एन्क्रिप्शन',
    editProfile: 'माहिती संपादित करा',
    saveProfile: 'बदल जतन करा',
    fullName: 'पूर्ण नाव',
    fatherName: 'वडिलांचे नाव',
    mobile: 'मोबाइल नंबर',
    email: 'ईमेल पत्ता',
    state: 'राज्य',
    district: 'जिल्हा',
    annualIncome: 'वार्षिक कौटुंबिक उत्पन्न',
    institution: 'शिक्षण संस्था',
    course: 'अभ्यासक्रम / पदवी',
    rollNo: 'रोल नंबर',
    bankName: 'बँकेचे नाव',
    accountNo: 'खाते क्रमांक',
    ifsc: 'IFSC कोड',
    dbtActive: 'आधार डीबीटी सक्रिय',

    // Bottom Nav
    navHome: 'मुख्य',
    navSchemes: 'योजना',
    navTrack: 'ट्रॅक करा',
    navDocs: 'कागदपत्रे',
    navProfile: 'प्रोफाइल',

    // Quick Actions
    actionApply: 'अर्ज करा',
    actionExplore: 'योजना शोधा',
    actionTrack: 'स्थिती ट्रॅक करा',
    actionWallet: 'कागदपत्रे पाकीट',
    actionJago: 'जागो सहाय्यक',
    actionEligibility: 'पात्रता तपासा',

    // Assistant
    chatbotGreeting: 'नमस्ते! 🙏 मी जागो (JAGO) आहे, आदिवासी कार्य मंत्रालयाचा शिष्यवृत्ती सहाय्यक. मी आज आपल्याला कशी मदत करू शकतो?',
    chatbotPlaceholder: 'शिष्यवृत्तीबद्दल कोणताही प्रश्न विचारा...',
    chatbotSend: 'पाठवा',

    // Settings & Notifications
    language: 'भाषा (Language)',
    changeLanguage: 'अ‍ॅपची भाषा बदला',
    currentLanguage: 'सध्याची भाषा',
    notificationsTitle: 'सूचना केंद्र',
    markAllRead: 'सर्व वाचलेले म्हणून चिन्हांकित करा',
  },

  te: {
    appTitle: 'జాగో (JAGO)',
    appSubtitle: 'గిరిజన విద్యార్థుల సమగ్ర స్కాలర్‌షిప్ పోర్టల్',
    ministryTitle: 'గిరిజన వ్యవహారాల మంత్రిత్వ శాఖ • భారత ప్రభుత్వం',
    oneStudentSubtitle: 'ఒక విద్యార్థి. ఒక వీక్షణ. పునరావృతం లేదు.',
    offlineModeActive: 'ఆఫ్‌లైన్ మోడ్ యాక్టివ్: స్థానిక డేటా సురక్షితం',
    welcome: 'నమస్కారం',
    verified: 'ఆధార్ ధృవీకరించబడింది',
    disbursed: 'మొత్తం జమ (DBT)',
    sanctioned: 'మంజూరు చేయబడింది (పెండింగ్)',
    creditedToSbi: 'బ్యాంకు ఖాతాలో జమయింది',
    underReview: 'రాబోయే డీబీటీ చెల్లింపు',
    quickServices: 'త్వరిత సేవలు',
    viewAllSchemes: 'అన్ని 5 పథకాలు →',
    myApplications: 'నా దరఖాస్తులు',
    noApps: 'ఇంకా దరఖాస్తులు లేవు',
    exploreApply: 'వెతకండి & దరఖాస్తు చేసుకోండి',
    appliedOn: 'దరఖాస్తు తేదీ',
    viewTimeline: 'పురోగతి చూడండి',
    nationalImpact: 'గిరిజన వ్యవహారాల మంత్రిత్వ శాఖ • జాతీయ డీబీటీ ప్రభావం',
    dbtHistory: 'ప్రత్యక్ష లబ్ధి బదిలీ (DBT) చరిత్ర',
    recentApplications: 'ఇటీవలి దరఖాస్తులు',
    actionRequired: 'చర్య అవసరం',
    deficiencyNotice: 'లోపం నోటీసు (Deficiency)',
    rectifyNow: 'ఇప్పుడే సరిచేయండి',
    fixViaWallet: 'వాలెట్ ద్వారా పరిష్కరించండి →',

    // Scheme Directory
    exploreSchemes: 'ఎస్టీ స్కాలర్‌షిప్ పథకాలను అన్వేషించండి',
    schemeDirectory: 'సమగ్ర పథకాల డైరెక్టరీ',
    motaCentralSchemes: '5 కేంద్ర గిరిజన మంత్రిత్వ శాఖ పథకాలు',
    searchSchemesPlaceholder: 'పథకం పేరు, డిగ్రీ లేదా సంస్థ ద్వారా శోధించండి...',
    filterAll: 'అన్ని పథకాలు',
    filterNsp: 'NSP పోర్టల్',
    filterSfmp: 'SFMP (కెనరా)',
    filterNos: 'NOS పోర్టల్',
    daysLeft: 'రోజులు మిగిలి ఉన్నాయి',
    deadlinePassed: 'గడువు ముగిసింది',
    applyNow: 'దరఖాస్తు చేసుకోండి',
    academicYear: 'విద్యా సంవత్సరం',
    noSchemesFound: 'ఏ పథకం సరిపోలలేదు.',

    // Document Wallet
    docWalletTitle: 'పత్రాల వాలెట్',
    syncDigilocker: 'డిజిలాకర్‌తో సింక్ చేయండి',
    uploadNewDoc: 'కొత్త పత్రాన్ని అప్‌లోడ్ చేయండి',
    digilockerVerified: 'డిజిలాకర్ ధృవీకరించబడింది',
    zeroKnowledgeEncrypted: 'జీరో-నాలెడ్జ్ ఎన్‌క్రిప్ట్ చేయబడింది (AES-256)',
    catAll: 'అన్ని పత్రాలు',
    catIdentity: 'గుర్తింపు రుజువు',
    catCaste: 'కుల ధృవీకరణ పత్రం',
    catIncome: 'ఆదాయ ధృవీకరణ పత్రం',
    catAcademic: 'విద్యా మార్కుల జాబితా',

    // Application Tracker
    trackerTitle: 'దరఖాస్తు ట్రాకర్',
    activeApplications: 'యాక్టివ్ దరఖాస్తులు',
    noActiveApplications: 'యాక్టివ్ దరఖాస్తులు కనుగొనబడలేదు.',
    stage1: 'రిజిస్ట్రేషన్ & గుర్తింపు ధృవీకరణ',
    stage2: 'సంస్థ AISHE ధృవీకరణ',
    stage3: 'రాష్ట్ర గిరిజన సంక్షేమ శాఖ ధృవీకరణ',
    stage4: 'కేంద్ర మంత్రిత్వ శాఖ మంజూరు ఉత్తర్వు',
    stage5: 'బ్యాంకు ఖాతాకు నేరుగా డీబీటీ బదిలీ',
    statusSanctioned: 'మంజూరు చేయబడింది',
    statusDisbursed: 'జమ చేయబడింది',
    statusDeficiency: 'లోపం',
    statusPending: 'పెండింగ్',
    statusApproved: 'ఆమోదించబడింది',
    statusCompleted: 'పూర్తయింది',
    statusInProgress: 'పురోగతిలో ఉంది',

    // Profile
    profileTitle: 'దరఖాస్తుదారు ప్రొఫైల్',
    personalDetails: 'వ్యక్తిగత సమాచారం',
    tribalDetails: 'గిరిజన & కమ్యూనిటీ వివరాలు',
    educationDetails: 'ప్రస్తుత విద్య నమోదు',
    bankDetails: 'డీబీటీ బ్యాంకు ఖాతా',
    securityEncryption: 'భద్రత & జీరో-నాలెడ్జ్ ఎన్‌క్రిప్షన్',
    editProfile: 'వివరాలను సవరించండి',
    saveProfile: 'మార్పులను సేవ్ చేయండి',
    fullName: 'పూర్తి పేరు',
    fatherName: 'తండ్రి పేరు',
    mobile: 'మొబైల్ నంబర్',
    email: 'ఈమెయిల్ చిరునామా',
    state: 'రాష్ట్రం',
    district: 'జిల్లా',
    annualIncome: 'వార్షిక కుటుంబ ఆదాయం',
    institution: 'విద్యా సంస్థ',
    course: 'కోర్సు / ప్రోగ్రామ్',
    rollNo: 'రోల్ నంబర్',
    bankName: 'బ్యాంకు పేరు',
    accountNo: 'ఖాతా నంబర్',
    ifsc: 'IFSC కోడ్',
    dbtActive: 'ఆధార్ డీబీటీ యాక్టివ్',

    // Bottom Nav
    navHome: 'హోమ్',
    navSchemes: 'పథకాలు',
    navTrack: 'ట్రాక్',
    navDocs: 'పత్రాలు',
    navProfile: 'ప్రొఫైల్',

    // Quick Actions
    actionApply: 'దరఖాస్తు చేసుకోండి',
    actionExplore: 'పథకాలు అన్వేషించండి',
    actionTrack: 'స్థితిని ట్రాక్ చేయండి',
    actionWallet: 'డాక్ వాలెట్',
    actionJago: 'జాగో అసిస్టెంట్',
    actionEligibility: 'అర్హత తనిఖీ',

    // Assistant
    chatbotGreeting: 'నమస్కారం! 🙏 నేను జాగో (JAGO), గిరిజన వ్యవహారాల మంత్రిత్వ శాఖ స్కాలర్‌షిప్ అసిస్టెంట్. నేను మీకు ఎలా సహాయపడగలను?',
    chatbotPlaceholder: 'స్కాలర్‌షిప్ గురించి ఏదైనా అడగండి...',
    chatbotSend: 'పంపండి',

    // Settings & Notifications
    language: 'భాష (Language)',
    changeLanguage: 'యాప్ భాషను మార్చండి',
    currentLanguage: 'ప్రస్తుత భాష',
    notificationsTitle: 'నోటిఫికేషన్ సెంటర్',
    markAllRead: 'అన్నీ చదివినట్లుగా గుర్తించండి',
  },

  ta: {
    appTitle: 'ஜாகோ (JAGO)',
    appSubtitle: 'பழங்குடியின மாணவர்களுக்கான ஒருங்கிணைந்த கல்வி உதவித்தொகை',
    ministryTitle: 'பழங்குடியினர் விவகார அமைச்சகம் • இந்திய அரசு',
    oneStudentSubtitle: 'ஒரு மாணவர். ஒரு தளம். மறுமுறை இல்லை.',
    offlineModeActive: 'ஆஃப்லைன் முறை செயலில்: உள்ளூர் தரவு பாதுகாப்பானது',
    welcome: 'வணக்கம்',
    verified: 'ஆதார் சரிபார்க்கப்பட்டது',
    disbursed: 'வழங்கப்பட்டது (DBT)',
    sanctioned: 'ஒப்புதல் அளிக்கப்பட்டது (நிலுவையில்)',
    creditedToSbi: 'வங்கி கணக்கில் வரவு வைக்கப்பட்டது',
    underReview: 'எதிர்பார்க்கப்படும் டிபிடி வரவு',
    quickServices: 'விரைவு சேவைகள்',
    viewAllSchemes: 'அனைத்து 5 திட்டங்கள் →',
    myApplications: 'எனது விண்ணப்பங்கள்',
    noApps: 'விண்ணப்பங்கள் எதுவும் இல்லை',
    exploreApply: 'ஆராய்ந்து விண்ணப்பிக்கவும்',
    appliedOn: 'விண்ணப்பித்த தேதி',
    viewTimeline: 'காலவரிசையைக் காண்க',
    nationalImpact: 'பழங்குடியினர் விவகார அமைச்சகம் • தேசிய டிபிடி தாக்கம்',
    dbtHistory: 'நேரடி பலன் பரிமாற்றம் (DBT) வரலாறு',
    recentApplications: 'சமீபத்திய விண்ணப்பங்கள்',
    actionRequired: 'நடவடிக்கை தேவை',
    deficiencyNotice: 'குறைபாடு அறிவிப்பு',
    rectifyNow: 'இப்போதே சரிசெய்யவும்',
    fixViaWallet: 'வாலெட் மூலம் சரிசெய்யவும் →',

    // Scheme Directory
    exploreSchemes: 'பழங்குடியினர் கல்வி உதவித்தொகை திட்டங்கள்',
    schemeDirectory: 'ஒருங்கிணைந்த திட்ட கையேடு',
    motaCentralSchemes: '5 மத்திய பழங்குடியினர் அமைச்சக திட்டங்கள்',
    searchSchemesPlaceholder: 'திட்டத்தின் பெயர், பட்டம் அல்லது கல்லூரி தேடுக...',
    filterAll: 'அனைத்து திட்டங்கள்',
    filterNsp: 'NSP போர்டல்',
    filterSfmp: 'SFMP (கனரா)',
    filterNos: 'NOS போர்டல்',
    daysLeft: 'நாட்கள் மீதமுள்ளன',
    deadlinePassed: 'காலக்கெடு முடிந்தது',
    applyNow: 'விண்ணப்பிக்கவும்',
    academicYear: 'கல்வியாண்டு',
    noSchemesFound: 'எந்த திட்டமும் பொருந்தவில்லை.',

    // Document Wallet
    docWalletTitle: 'ஆவணப் பை',
    syncDigilocker: 'டிஜிலாக்கருடன் இணைக்கவும்',
    uploadNewDoc: 'புதிய ஆவணத்தை பதிவேற்றவும்',
    digilockerVerified: 'டிஜிலாக்கர் சரிபார்க்கப்பட்டது',
    zeroKnowledgeEncrypted: 'பூஜ்ஜிய-அறிவு மறைகுறியாக்கம் (AES-256)',
    catAll: 'அனைத்து ஆவணங்கள்',
    catIdentity: 'அடையாளச் சான்று',
    catCaste: 'சாதிச் சான்றிதழ்',
    catIncome: 'வருமானச் சான்றிதழ்',
    catAcademic: 'கல்வி மதிப்பெண் பட்டியல்',

    // Application Tracker
    trackerTitle: 'விண்ணப்ப கண்காணிப்பு',
    activeApplications: 'செயலில் உள்ள விண்ணப்பங்கள்',
    noActiveApplications: 'செயலில் உள்ள விண்ணப்பங்கள் எதுவும் இல்லை.',
    stage1: 'பதிவு மற்றும் அடையாள சரிபார்ப்பு',
    stage2: 'நிறுவன AISHE அங்கீகாரம்',
    stage3: 'மாநில பழங்குடியினர் துறை சரிபார்ப்பு',
    stage4: 'மத்திய அமைச்சக அனுமதி உத்தரவு',
    stage5: 'வங்கி கணக்கில் நேரடி டிபிடி வரவு',
    statusSanctioned: 'அங்கீகரிக்கப்பட்டது',
    statusDisbursed: 'வழங்கப்பட்டது',
    statusDeficiency: 'குறைபாடு',
    statusPending: 'நிலுவையில்',
    statusApproved: 'ஒப்புதல் அளிக்கப்பட்டது',
    statusCompleted: 'முடிந்தது',
    statusInProgress: 'செயலில் உள்ளது',

    // Profile
    profileTitle: 'விண்ணப்பதாரர் சுயவிவரம்',
    personalDetails: 'தனிப்பட்ட தகவல்',
    tribalDetails: 'பழங்குடி & சமூக விவரங்கள்',
    educationDetails: 'தற்போதைய கல்வி சேர்க்கை',
    bankDetails: 'டிபிடி வங்கி கணக்கு',
    securityEncryption: 'பாதுகாப்பு & பூஜ்ஜிய-அறிவு மறைகுறியாக்கம்',
    editProfile: 'சுயவிவரத்தை திருத்தவும்',
    saveProfile: 'மாற்றங்களை சேமிக்கவும்',
    fullName: 'முழு பெயர்',
    fatherName: 'தந்தையின் பெயர்',
    mobile: 'கைபேசி எண்',
    email: 'மின்னஞ்சல் முகவரி',
    state: 'மாநிலம்',
    district: 'மாவட்டம்',
    annualIncome: 'ஆண்டு குடும்ப வருமானம்',
    institution: 'கல்வி நிறுவனம்',
    course: 'படிப்பு / பாடப்பிரிவு',
    rollNo: 'பதிவு எண்',
    bankName: 'வங்கி பெயர்',
    accountNo: 'கணக்கு எண்',
    ifsc: 'IFSC குறியீடு',
    dbtActive: 'ஆதார் டிபிடி செயலில் உள்ளது',

    // Bottom Nav
    navHome: 'முகப்பு',
    navSchemes: 'திட்டங்கள்',
    navTrack: 'கண்காணிப்பு',
    navDocs: 'ஆவணங்கள்',
    navProfile: 'சுயவிவரம்',

    // Quick Actions
    actionApply: 'விண்ணப்பிக்கவும்',
    actionExplore: 'திட்டங்களை ஆராய்க',
    actionTrack: 'நிலையைக் கண்காணிக்கவும்',
    actionWallet: 'ஆவணப் பை',
    actionJago: 'ஜாகோ உதவியாளர்',
    actionEligibility: 'தகுதியை சரிபார்க்கவும்',

    // Assistant
    chatbotGreeting: 'வணக்கம்! 🙏 நான் ஜாகோ (JAGO), பழங்குடியினர் விவகார அமைச்சகத்தின் கல்வி உதவித்தொகை உதவியாளர். இன்று நான் உங்களுக்கு எவ்வாறு உதவ முடியும்?',
    chatbotPlaceholder: 'கல்வி உதவித்தொகை பற்றி எதையும் கேளுங்கள்...',
    chatbotSend: 'அனுப்பவும்',

    // Settings & Notifications
    language: 'மொழி (Language)',
    changeLanguage: 'பயன்பாட்டின் மொழியை மாற்றவும்',
    currentLanguage: 'தற்போதைய மொழி',
    notificationsTitle: 'அறிவிப்பு மையம்',
    markAllRead: 'அனைத்தையும் படித்ததாகக் குறிக்கவும்',
  },

  gu: {
    appTitle: 'જાગો (JAGO)',
    appSubtitle: 'જનજાતીય વિદ્યાર્થીઓ માટે સંકલિત શિષ્યવૃત્તિ પોર્ટલ',
    ministryTitle: 'જનજાતીય બાબતોનું મંત્રાલય • ભારત સરકાર',
    oneStudentSubtitle: 'એક વિદ્યાર્થી. એક દૃશ્ય. શૂન્ય પુનરાવર્તન.',
    offlineModeActive: 'ઑફલાઇન મોડ સક્રિય: સ્થાનિક ડેટા સુરક્ષિત',
    welcome: 'નમસ્તે',
    verified: 'આધાર પ્રમાણિત',
    disbursed: 'જમા થયેલ રકમ (DBT)',
    sanctioned: 'મંજૂર થયેલ (પ્રક્રિયામાં)',
    creditedToSbi: 'બેંક ખાતામાં જમા',
    underReview: 'અપેક્ષિત ડીબીટી જમા',
    quickServices: 'ઝડપી સેવાઓ',
    viewAllSchemes: 'બધી ૫ યોજનાઓ →',
    myApplications: 'મારી અરજીઓ',
    noApps: 'હજી સુધી કોઈ અરજી નથી',
    exploreApply: 'શોધો અને અરજી કરો',
    appliedOn: 'અરજી તારીખ',
    viewTimeline: 'સ્થિતિ જુઓ',
    nationalImpact: 'જનજાતીય બાબતોનું મંત્રાલય • રાષ્ટ્રીય ડીબીટી અસર',
    dbtHistory: 'ડાયરેક્ટ બેનિફિટ ટ્રાન્સફર (DBT) ઇતિહાસ',
    recentApplications: 'તાજેતરની અરજીઓ',
    actionRequired: 'પગલાં જરૂરી',
    deficiencyNotice: 'ક્ષતિ નોટિસ (Deficiency)',
    rectifyNow: 'હમણાં સુધારો',
    fixViaWallet: 'વૉલેટમાંથી સુધારો →',

    // Scheme Directory
    exploreSchemes: 'જનજાતીય શિષ્યવૃત્તિ યોજનાઓ શોધો',
    schemeDirectory: 'સંકલિત યોજના ડિરેક્ટરી',
    motaCentralSchemes: '૫ કેન્દ્રીય જનજાતીય મંત્રાલય યોજનાઓ',
    searchSchemesPlaceholder: 'યોજનાનું નામ, ડિગ્રી અથવા સંસ્થા શોધો...',
    filterAll: 'બધી યોજનાઓ',
    filterNsp: 'NSP પોર્ટલ',
    filterSfmp: 'SFMP (કેનરા)',
    filterNos: 'NOS પોર્ટલ',
    daysLeft: 'દિવસો બાકી',
    deadlinePassed: 'સમયમર્યાદા સમાપ્ત',
    applyNow: 'અરજી કરો',
    academicYear: 'શૈક્ષણિક વર્ષ',
    noSchemesFound: 'કોઈ યોજના મેળ ખાતી નથી.',

    // Document Wallet
    docWalletTitle: 'દસ્તાવેજ વૉલેટ',
    syncDigilocker: 'ડિજીલોકર સાથે સિંક કરો',
    uploadNewDoc: 'નવો દસ્તાવેજ અપલોડ કરો',
    digilockerVerified: 'ડિજીલોકર પ્રમાણિત',
    zeroKnowledgeEncrypted: 'ઝીરો-નોલેજ એન્ક્રિપ્ટેડ (AES-256)',
    catAll: 'બધા દસ્તાવેજો',
    catIdentity: 'ઓળખનો પુરાવો',
    catCaste: 'જાતિનું પ્રમાણપત્ર',
    catIncome: 'આવકનું પ્રમાણપત્ર',
    catAcademic: 'શૈક્ષણિક માર્કશીટ',

    // Application Tracker
    trackerTitle: 'અરજી ટ્રેકર',
    activeApplications: 'સક્રિય અરજીઓ',
    noActiveApplications: 'કોઈ સક્રિય અરજી મળી નથી.',
    stage1: 'નોંધણી અને ઓળખ ચકાસણી',
    stage2: 'સંસ્થા AISHE પ્રમાણીકરણ',
    stage3: 'રાજ્ય જનજાતીય વિભાગ ચકાસણી',
    stage4: 'કેન્દ્રીય મંત્રાલય મંજૂરી આદેશ',
    stage5: 'બેંક ખાતામાં સીધું ડીબીટી ટ્રાન્સફર',
    statusSanctioned: 'મંજૂર',
    statusDisbursed: 'વિતરિત',
    statusDeficiency: 'ક્ષતિ',
    statusPending: 'બાકી',
    statusApproved: 'મંજૂર થયેલ',
    statusCompleted: 'પૂર્ણ',
    statusInProgress: 'પ્રગતિમાં',

    // Profile
    profileTitle: 'અરજદાર પ્રોફાઇલ',
    personalDetails: 'વ્યક્તિગત માહિતી',
    tribalDetails: 'જનજાતીય અને સમુદાય વિગતો',
    educationDetails: 'હાલનું શૈક્ષણિક નામાંકન',
    bankDetails: 'ડીબીટી બેંક ખાતું',
    securityEncryption: 'સુરક્ષા અને ઝીરો-નોલેજ એન્ક્રિપ્શન',
    editProfile: 'વિગતો સંપાદિત કરો',
    saveProfile: 'ફેરફારો સાચવો',
    fullName: 'પૂરું નામ',
    fatherName: 'પિતાનું નામ',
    mobile: 'મોબાઇલ નંબર',
    email: 'ઇમેઇલ સરનામું',
    state: 'રાજ્ય',
    district: 'જિલ્લો',
    annualIncome: 'વાર્ષિક પારિવારિક આવક',
    institution: 'શિક્ષણ સંસ્થા',
    course: 'અભ્યાસક્રમ / ડિગ્રી',
    rollNo: 'રોલ નંબર',
    bankName: 'બેંકનું નામ',
    accountNo: 'ખાતા નંબર',
    ifsc: 'IFSC કોડ',
    dbtActive: 'આધાર ડીબીટી સક્રિય',

    // Bottom Nav
    navHome: 'હોમ',
    navSchemes: 'યોજનાઓ',
    navTrack: 'ટ્રેક',
    navDocs: 'દસ્તાવેજો',
    navProfile: 'પ્રોફાઇલ',

    // Quick Actions
    actionApply: 'અરજી કરો',
    actionExplore: 'યોજનાઓ શોધો',
    actionTrack: 'સ્થિતિ તપાસો',
    actionWallet: 'દસ્તાવેજ વૉલેટ',
    actionJago: 'જાગો સહાયક',
    actionEligibility: 'પાત્રતા ચકાસો',

    // Assistant
    chatbotGreeting: 'નમસ્તે! 🙏 હું જાગો (JAGO) છું, જનજાતીય બાબતોના મંત્રાલયનો શિષ્યવૃત્તિ સહાયક. હું આજે તમને કેવી રીતે મદદ કરી શકું?',
    chatbotPlaceholder: 'શિષ્યવૃત્તિ વિશે કંઈપણ પૂછો...',
    chatbotSend: 'મોકલો',

    // Settings & Notifications
    language: 'ભાષા (Language)',
    changeLanguage: 'એપ્લિકેશનની ભાષા બદલો',
    currentLanguage: 'હાલની ભાષા',
    notificationsTitle: 'સૂચના કેન્દ્ર',
    markAllRead: 'બધા વંચાયેલા તરીકે ચિહ્નિત કરો',
  },
};

export const getTranslation = (key, lang = 'en', fallbackText = '') => {
  const currentLang = translations[lang] || translations.en;
  if (currentLang && currentLang[key]) {
    return currentLang[key];
  }
  if (translations.en && translations.en[key]) {
    return translations.en[key];
  }
  return fallbackText || key;
};
